#!/bin/bash

cat <<- EOF > /etc/logrotate.d/freepbx-contactmanager
/var/log/asterisk/contactmanager_module_hook.log{
	size 50M
	missingok
	rotate 5
	notifempty
	sharedscripts
	dateext
	create 0640 asterisk asterisk
	su asterisk asterisk
}
EOF
