#!/usr/bin/php -q
<?php
    require '/usr/lib/sysadmin/includes.php';
    if (!@include_once(getenv('FREEPBX_CONF') ? getenv('FREEPBX_CONF') : '/etc/freepbx.conf')) {
        include_once('/etc/asterisk/freepbx.conf');
    }
    $freepbx = \FreePBX::Create();
    $astman = $freepbx->astman;

    // Make sure we have a param
    if (empty($argv[1])) {
        throw new \Exception("Needs a param");
    }
    
    // Underp the base64 that the param is using.
    $b = str_replace('_', '/', $argv[1]);
    $userIdArray = @json_decode(gzuncompress(@base64_decode($b)), true);
    
    if (!is_array($userIdArray)) {
        throw new \Exception("Invalid param");
    }

    $logfd = fopen($freepbx->Config->get('ASTLOGDIR') . "/contactmanager_module_hook.log", "a+");
    fwrite($logfd, "\n\n" . "Reload Contacts Hook Started..." . "\n");
    if (count($userIdArray) == 1 && $userIdArray[0] == -1) {
        $users = $freepbx->userman->getAllUsers();
        foreach ($users as $index => $user) {
            //generate contact file of the user
            fwrite($logfd, "\n" . date('d/m/Y H:i:s') . " - Generating contact file for the user " . $user['username'] . "\n");
            $freepbx->Contactmanager->generateUserContacts($user['id']);
            fwrite($logfd, "Contact file generated" . "\n");
            fwrite($logfd, "Event dispatched for the user " . $user['username'] . "\n");
            //This user event is for Sangoma Connect Desktop Clients.
            //SwitchboardAlert-reloadContacts UserEvents will trigger the clients to redownload their contacts file.
            $res =  $astman->send_request("UserEvent", array(
                "UserEvent" => "SwitchboardAlert",
                "Alert" => 'reloadContacts',
                "AccountID" => $user['id'],
                "ActionID" => $user['id'] . time()
            ));
            fwrite($logfd, json_encode($res) . "\n");
            if ($index % 100 == 0) {
                sleep(2);
            }
        }
    } else {
        foreach ($userIdArray as $index => $userId) {
            $user = $freepbx->userman->getUserByID($userId);
            //generate contact file of the user
            fwrite($logfd, "\n" . date('d/m/Y H:i:s') . " - Generating contact file for the user " . $user['username'] . "\n");
            $freepbx->Contactmanager->generateUserContacts($user['id']);
            fwrite($logfd, "Contact file generated" . "\n");
            fwrite($logfd, "Event dispatched for the user " . $user['username'] . "\n");
            //This user event is for Sangoma Connect Desktop Clients.
            //SwitchboardAlert-reloadContacts UserEvents will trigger the clients to redownload their contacts file.
            $res =  $astman->send_request("UserEvent", array(
                "UserEvent" => "SwitchboardAlert",
                "Alert" => 'reloadContacts',
                "AccountID" => $user['id'],
                "ActionID" => $user['id'] . time()
            ));
            fwrite($logfd, json_encode($res) . "\n");
            if ($index % 100 == 0) {
                sleep(2);
            }
        }
    }
?>
